
resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
  imageRepository: 'nushapiggymetrics'
  containerRegistry: 'usharegistry.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'usharegistryf8c8-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'NUshapiggymetrics.piggymetrics'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Container Registry'
              dockerComposeFile: 'docker-compose.yml'
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              action: 'Build Services'

          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Container Registry'
              dockerComposeFile: 'docker-compose.yml'
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              action: 'Push Services'
              
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            inputs:
              action: 'bake'
              renderType: 'kompose'
              dockerComposeFile: docker-compose.yml
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: $(bake.manifestsBundle) 
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
