apiVersion: v1
kind: ConfigMap
metadata:
    name: configmap 
data:
  # Configuration values can be set as key-value properties
  CONFIG_SERVICE_PASSWORD: password
  NOTIFICATION_SERVICE_PASSWORD: password
  STATISTICS_SERVICE_PASSWORD: password
  ACCOUNT_SERVICE_PASSWORD: password
  MONGODB_URI: password  
  RABBITMQ_PASSWORD: password
  MONGODB_PASSWORD: password
