apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: nushapiggymetricsks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nushapiggymetricsks 
    spec:
      containers:
        - name: nushapiggymetricsks 
          image: usharegistry.azurecr.io/nushapiggymetricsks 
          ports:
          - containerPort: 6000