apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: account-service
  spec:
    ports:
    - name: "6000"
      port: 6000
      targetPort: 6000
    selector:
        app: account-service
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: auth-service
  spec:
    ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
    selector:
        app: auth-service
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: config
  spec:
    ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
    type: LoadBalancer
    selector:
        app: config
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: gateway
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 4000
    type: LoadBalancer
    selector:
        app: gateway
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: notification-service
  spec:
    ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    selector:
        app: notification-service
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: registry
  spec:
    ports:
    - name: "8761"
      port: 8761
      targetPort: 32475
    type: LoadBalancer
    selector:
        app: registry
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: statistics-service
  spec:
    ports:
    - name: "7000"
      port: 7000
      targetPort: 7000
    selector:
        app: statistics-service
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: account-service
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: account-service
      spec:
        containers:
        - env:
          - name: ACCOUNT_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords 
                key: account-service-password
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords 
                key: config-service-password
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: piggy-passwords 
                key: mongodb-uri 
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: rabbitmq-password
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: mongodb
          - name: RABBITMQ_PORT
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: rabbitmq-port
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: rabbitmq-host
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: rabbitmq-username
          image: javademosregistry.azurecr.io/piggymetrics-account-service
          name: account-service
          ports:
          - containerPort: 6000
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: auth-service
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: auth-service
      spec:
        containers:
        - env:
          - name: ACCOUNT_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords 
                key: account-service-password
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords 
                key: config-service-password
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: mongodb-uri
          - name: NOTIFICATION_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: notification-service-password
          - name: STATISTICS_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: statistics-service-password
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: rabbitmq-password
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: mongodb
          image: javademosregistry.azurecr.io/piggymetrics-auth-service
          name: auth-service
          ports:
          - containerPort: 5000
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: config
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: config
      spec:
        containers:
        - env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: config-service-password
          image: javademosregistry.azurecr.io/piggymetrics-config
          name: config
          ports:
          - containerPort: 8888
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: gateway
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: gateway
      spec:
        containers:
        - env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: config-service-password
          image: javademosregistry.azurecr.io/piggymetrics-gateway
          name: gateway
          ports:
          - containerPort: 4000
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: notification-service
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: notification-service
      spec:
        containers:
        - env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: config-service-password
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: mongodb
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: mongodb-uri
          - name: NOTIFICATION_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: notification-service-password
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: rabbitmq-host
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: rabbitmq-password
          - name: RABBITMQ_PORT
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: rabbitmq-port
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: rabbitmq-username
          image: javademosregistry.azurecr.io/piggymetrics-notification-service
          name: notification-service
          ports:
          - containerPort: 8000
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: registry
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: registry
      spec:
        containers:
        - env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: config-service-password
          image: javademosregistry.azurecr.io/piggymetrics-registry
          name: registry
          ports:
          - containerPort: 8761
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: statistics-service
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: statistics-service
      spec:
        containers:
        - env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: config-service-password
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: mongodb
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: mongodb-uri
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: rabbitmq-host
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: rabbitmq-password
          - name: RABBITMQ_PORT
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: rabbitmq-port
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: piggy-config
                key: rabbitmq-username
          - name: STATISTICS_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-passwords
                key: statistics-service-password
          image: javademosregistry.azurecr.io/piggymetrics-statistics-service
          name: statistics-service
          ports:
          - containerPort: 7000
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}
