apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: account-service
  spec:
    ports:
    - name: "6000"
      port: 6000
      targetPort: 6000
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: auth-service
  spec:
    ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: config
  spec:
    ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: gateway
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 4000
    type: LoadBalancer
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: notification-service
  spec:
    ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: registry
  spec:
    ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: statistics-service
  spec:
    ports:
    - name: "7000"
      port: 7000
      targetPort: 7000
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: account-service
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: ACCOUNT_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: account-service-password
                key: ACCOUNT_SERVICE_PASSWORD
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: config-service-password
                key: CONFIG_SERVICE_PASSWORD
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb-uri
                key: MONGODB_URI 
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-password
                key: RABBITMQ_PASSWORD
          - name: MONGODB_DATABASE
          - name: RABBITMQ_PORT
          - name: RABBITMQ_HOST
          - name: RABBITMQ_USERNAME
          image: .azurecr.io/piggymetrics-account-service
          name: account-service
          ports:
          - containerPort: 6000
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: auth-service
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: ACCOUNT_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: account-service-password
                key: ACCOUNT_SERVICE_PASSWORD
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: config-service-password
                key: CONFIG_SERVICE_PASSWORD
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb-uri
                key: MONGODB_URI
          - name: NOTIFICATION_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: notification-service-password
                key: NOTIFICATION_SERVICE_PASSWORD
          - name: STATISTICS_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: statistics-service-password
                key: STATISTICS_SERVICE_PASSWORD
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-password
                key: RABBITMQ_PASSWORD
          - name: MONGODB_DATABASE
          image: .azurecr.io/piggymetrics-auth-service
          name: auth-service
          ports:
          - containerPort: 5000
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: config
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: config-service-password
                key: CONFIG_SERVICE_PASSWORD
          image: .azurecr.io/piggymetrics-config
          name: config
          ports:
          - containerPort: 8888
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: gateway
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: config-service-password
                key: CONFIG_SERVICE_PASSWORD
          image: .azurecr.io/piggymetrics-gateway
          name: gateway
          ports:
          - containerPort: 4000
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: notification-service
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: config-service-password
                key: CONFIG_SERVICE_PASSWORD
          - name: MONGODB_DATABASE
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb-uri
                key: MONGODB_URI
          - name: NOTIFICATION_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: notification-service-password
                key: NOTIFICATION_SERVICE_PASSWORD
          - name: RABBITMQ_HOST
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-password
                key: RABBITMQ_PASSWORD
          - name: RABBITMQ_PORT
          - name: RABBITMQ_USERNAME
          image: .azurecr.io/piggymetrics-notification-service
          name: notification-service
          ports:
          - containerPort: 8000
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: registry
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: config-service-password
                key: CONFIG_SERVICE_PASSWORD
          image: .azurecr.io/piggymetrics-registry
          name: registry
          ports:
          - containerPort: 8761
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: statistics-service
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: config-service-password
                key: CONFIG_SERVICE_PASSWORD
          - name: MONGODB_DATABASE
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb-uri
                key: MONGODB_URI
          - name: RABBITMQ_HOST
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-password
                key: RABBITMQ_PASSWORD
          - name: RABBITMQ_PORT
          - name: RABBITMQ_USERNAME
          - name: STATISTICS_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: statistics-service-password
                key: STATISTICS_SERVICE_PASSWORD
          image: .azurecr.io/piggymetrics-statistics-service
          name: statistics-service
          ports:
          - containerPort: 7000
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}
