# This workflow will build a docker container, publish it to Azure Container Registry, and deploy it to Azure Kubernetes Service.
#
# To configure this workflow:
#
# 1. Set up the following secrets in your workspace: 
#     a. REGISTRY_USERNAME with ACR username
#     b. REGISTRY_PASSWORD with ACR Password
#     c. AZURE_CREDENTIALS with the output of `az ad sp create-for-rbac --sdk-auth`
#
# 2. Change the values for the REGISTRY_NAME, CLUSTER_NAME, CLUSTER_RESOURCE_GROUP and NAMESPACE environment variables (below).

on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: my-registry-name
  CLUSTER_NAME: aks4microservices
  CLUSTER_RESOURCE_GROUP: devops-java-microservices-to-aks
  NAMESPACE: piggymetrics
  CONTAINER_REGISTRY: javademosregistry
  MONGODB_DATABASE: piggymetrics
  RABBITMQ_RESOURCE_GROUP: rabbitmq
  RABBITMQ_USERNAME: rabbitmq
  RABBITMQ_HOST: 40.87.124.184
  RABBITMQ_PORT: 5672

  
jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
    
    # Create imagepullsecret for Azure Container registry (ACR)
    - uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: ${{ env.REGISTRY_NAME }}-registry-connection
        namespace: ${{ env.NAMESPACE }}
    
    # Create generic secrets to be available on pods
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE }}
        secret-type: 'generic'
        arguments: --from-literal=config-service-password=${{ secrets.CONFIG_SERVICE_PASSWORD }} --from-literal=notification-service-password=${{ secrets.NOTIFICATION_SERVICE_PASSWORD }} --from-literal=statistics-service-password=${{ secrets.STATISTICS_SERVICE_PASSWORD }} --from-literal=account-service-password=${{ secrets.ACCOUNT_SERVICE_PASSWORD }} --from-literal=rabbitmq-password=${{ secrets.RABBITMQ_PASSWORD }} --from-literal=mongodb-uri=${{ secrets.MONGODB_URI }}  
        secret-name: piggy-passwords
        
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE }}
        secret-type: 'generic'
        arguments: --from-literal=mongodb=${{ env.MONGODB_DATABASE }} --from-literal=rabbitmq-rg=${{ env.RABBITMQ_RESOURCE_GROUP }} --from-literal=rabbitmq-username=${{ env.RABBITMQ_USERNAME }} --from-literal=rabbitmq-host=${{ env.RABBITMQ_HOST }} --from-literal=rabbitmq-port=${{ env.RABBITMQ_PORT }} 
        secret-name: piggy-config      
    
    # Baking the docker-compose file using Kompose to generate the manifests to deploy
#     - uses: azure/k8s-bake@v1
#       with:
#         renderEngine: 'kompose'
#         dockerComposeFile: './docker-compose.yml'
#         kompose-version: 'latest'
#       id: bake
#       env:
#           MONGODB_DATABASE: piggymetrics
#           RABBITMQ_RESOURCE_GROUP: rabbitmq
#           RABBITMQ_USERNAME: rabbitmq
#           RABBITMQ_HOST: 40.87.124.184
#           RABBITMQ_PORT: 5672
          
#     - run: |
#         kubectl apply -f manifests/manifest.yml -n ${{ env.NAMESPACE }}
#       env:
#            CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
     
     # Start an instance of Spring Cloud Config
     
#     # Deploy app to AKS
    - uses: azure/k8s-deploy@replaceLogic
      with:
        manifests: manifests/manifest.yml 
        imagepullsecrets: |
          ${{ env.CONTAINER_REGISTRY }}-registry-connection
        namespace: ${{ env.NAMESPACE }}
